-- MySQL Script generated by MySQL Workbench
-- Thu Aug 13 09:39:46 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_noticia` DEFAULT CHARACTER SET utf8 ;
USE `sistema_noticia` ;

-- -----------------------------------------------------
-- Table `sistema_noticias`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_noticia`.`usuario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_noticia`.`noticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_noticia`.`noticia` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(10000) NOT NULL,
  `data` DATE NOT NULL,
  `imagem` VARCHAR(45) NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_noticia_usuario_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_noticia_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `sistema_noticia`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_noticias`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_noticia`.`comentario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `comentario` VARCHAR(1024) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `noticia_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_table1_noticia1_idx` (`noticia_id` ASC),
  CONSTRAINT `fk_table1_noticia1`
    FOREIGN KEY (`noticia_id`)
    REFERENCES `sistema_noticia`.`noticia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
